services:
    db:
        image: mariadb:11
        env_file:
            - ./docker/env/mariadb.env
            - ./docker/env/development.env
            - ./docker/env/mariadb-development.env
        ports:
            - "3306:3306"
        volumes:
            - mariadb-data-dev:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 10s
            timeout: 5s
            retries: 5

    cognis-dev:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: cognis:dev
        env_file:
            - ./docker/env/default.env
            - ./docker/env/mariadb.env
            - ./docker/env/development.env
            - ./docker/env/mariadb-development.env
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
            - node_modules_dev:/app/node_modules
            - applogs-dev:/app/logs
            - appconfig-dev:/app/config
        command: sh -c "npm ci --ignore-scripts && npm run start"
        depends_on:
            db:
                condition: service_healthy

volumes:
    mariadb-data-dev:
    node_modules_dev:
    applogs-dev:
    appconfig-dev:
