export const AVATAR_CROP_WIDTH_TO_HEIGHT_RATIO = 1;
export const PROFILE_BIO_MAX_CHARACTERS = 200;
export const PROFILE_DISPLAY_NAME_MAX_CHARACTERS = 80;
export const PROFILE_LOCATION_MAX_CHARACTERS = 120;
export const PROFILE_WEBSITE_MAX_CHARACTERS = 2048;
