user nginx;
worker_processes auto;
pid /run/nginx.pid;
load_module /usr/lib/nginx/modules/ngx_http_brotli_filter_module.so;
load_module /usr/lib/nginx/modules/ngx_http_brotli_static_module.so;

events {
    worker_connections 2048;
}

http {
    include /etc/nginx/mime.types;
    sendfile on;
    keepalive_timeout 65;
    keepalive_requests 1000;
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/json application/javascript text/css text/plain image/svg+xml;
    brotli on;
    brotli_comp_level 5;
    brotli_types application/json application/javascript text/css text/plain image/svg+xml;

    ssl_session_cache shared:CognisTLS:20m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;

    map $http_x_forwarded_proto $cognis_forwarded_proto {
        default $http_x_forwarded_proto;
        "" $scheme;
    }

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    upstream cognis_app {
        zone cognis_app 64k;
        server cognis:3000 resolve;
        keepalive 64;
    }

    include /etc/nginx/conf.d/*.conf;
}
